export const Data = [
    {id:1,
    FirstName : "vimal",
    LastName : "Raj",
    email :"vimal@gmail.com",
    MobileNumber:76745494535,
    dob : "12.12.1998",
    // Gender : "male",
    Status : "ACTIVE",
    Address :"Haii vimal"},

    {id:2,
    FirstName : "Santhosh",
    LastName : "Mathan",
    email :"Santhosh@gmail.com",
    MobileNumber:76745494535,
    dob : "12.12.1992",
    // Gender : "male",
    Status : "ACTIVE",
    Address :"Haii Santhosh"},
        {id:3,
        FirstName : "vimalvr",
        LastName : "Raj",
        email :"vimal@gmail.com",
        MobileNumber:76745494535,
        dob : "12.12.1998",
        // Gender : "male",
        Status : "ACTIVE",
        Address :"Haii vimalvr"},
    
        {id:4,
        FirstName : "Mathan",
        LastName : "Mathan",
        email :"Mathan@gmail.com",
        MobileNumber:76745494535,
        dob : "12.12.1992",
        // Gender : "male",
        Status : "ACTIVE",
        Address :"Haii Mathan"},
            {id:5,
            FirstName : "Sanjai",
            LastName : "Velan",
            email :"Sanjai@gmail.com",
            MobileNumber:76745494535,
            dob : "12.12.1998",
            // Gender : "male",
            Status : "ACTIVE",
            Address :"Haii Sanjai"},
        
            {id:6,
            FirstName : "Velan",
            LastName : "Mathan",
            email :"Velan@gmail.com",
            MobileNumber:76745494535,
            dob : "12.12.1992",
            // Gender : "male",
            Status : "ACTIVE",
            Address :"Haii Velan"},
                {id:7,
                FirstName : "Raj",
                LastName : "Kumar",
                email :"Raj@gmail.com",
                MobileNumber:76745494535,
                dob : "12.12.1998",
                // Gender : "male",
                Status : "ACTIVE",
                Address :"Haii Raj"},
            
                {id:8,
                FirstName : "MathanV",
                LastName : "Mathan",
                email :"MathanV@gmail.com",
                MobileNumber:76745494535,
                dob : "12.12.1992",
                // Gender : "male",
                Status : "ACTIVE",
                Address :"Haii MathanV"}];